name: Test env

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Use node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
      - name: Generate build
        run: |
          npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: next-github-actions-build
          path: .next
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploying the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          port: ${{ secrets.TEST_PORT }}
          key: ${{ secrets.TEST_KEY }}
          passphrase: ${{ secrets.TEST_PASSPHRASE }}
          password: ${{ secrets.TEST_PASSWORD }}
          script: |
            
       
